networks:
  sawmill:
    name: sawmill

services:
  api:
    image: sawmill/api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./sawmill_api/:/usr/local/lib/python3.12/site-packages/sawmill_api/
  oltp:
    image: cockroachdb/cockroach:latest-v25.2
    ports:
      - "8080:8080"
      - "26257:26257"
    environment:
      - COCKROACH_DATABASE=sawmill
      - COCKROACH_USER=sawmill
      - COCKROACH_PASSWORD=a
    command:
      - start-single-node
      - --http-addr=oltp:8080
